---
name: Build
permissions:
  contents: read

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-macos:
    runs-on: macos-15
    env:
      CI_VERSION: ${{ github.sha }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          submodules: 'recursive'
          fetch-depth: 1

      - name: Install create-dmg
        run: |
          brew install node
          npm install --global create-dmg

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          cache: true
          version: 6.10.2
          aqtsource: 'git+https://github.com/miurahr/aqtinstall.git@9edeb24ae65361fd032a063a0b0148764eff09c5'

      - name: Build and Package
        run: bash scripts/generate-dmg.sh Release
